name: timemanager
description: Pomodoro facilitator

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.9.0
  shared_preferences: ^0.5.12
  shared_preferences_web: ^0.1.2+7
  intl: ^0.16.0
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
